language: java
before_script: cd CaloriesRecordingSystem
script:
- mvn -Dmaven.test.failure.ignore=true --fail-at-end clean install
- mvn failsafe:integration-test
jdk:
- oraclejdk8
notifications:
  email: false
